<?php
/**
 * XML Sitemaps Manager admin help tab.
 *
 * @package XML Sitemaps Manager
 */

?>
<p>
	<?php esc_html_e( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.', 'xml-sitemaps-manager' ); ?>
	<?php esc_html_e( 'Managed and extended by XML Sitemaps Manager to improve performance and search engine visibility.', 'xml-sitemaps-manager' ); ?>
	<?php esc_html_e( 'The XML Sitemaps list the web pages of your site to tell search engines about the organization of your site content. Search engine web crawlers read this file to more intelligently crawl your site.', 'xml-sitemaps-manager' ); ?>
	<a href="https://www.sitemaps.org/" target="_blank">
		<?php esc_html_e( 'Learn more about XML sitemaps.', 'xml-sitemaps-manager' ); ?>
	</a>
</p>
<ul>
	<li>
		<?php esc_html_e( 'When your site is public, all XML sitemaps are enabled by default. You can disable the main sitemap index or disable individual sitemaps.', 'xml-sitemaps-manager' ); ?>
	</li>
	<li>
		<?php esc_html_e( 'You can adapt the maximum number of URLs per sitemap. Decrease that number if you encounter errors, increase it if your sitemap index contains too many sitemaps.', 'xml-sitemaps-manager' ); ?>
	</li>
	<li>
		<?php esc_html_e( 'You can add Last Modified data to the sitemaps. Note that this will cause some additional database queries for certain sitemaps. If you encounter errors, try decreasing the maximum number of URLs per sitemap or disable this option.', 'xml-sitemaps-manager' ); ?>
	</li>
</ul>
<hr />
<p class="description">
	<?php
	printf(
		/* translators: %1$s Plugin name, %2$s Support forum on WordPress.org (linked) */
		esc_html__( 'These options are provided by %1$s. For help, please go to %2$s.', 'xml-sitemaps-manager' ),
		'<strong>' . esc_html__( 'XML Sitemaps Manager', 'xml-sitemaps-manager' ) . '</strong>',
		'<a href="https://wordpress.org/support/plugin/xml-sitemaps-manager/" target="_blank">' . esc_html__( 'Support' ) . '</a>'
	);
	?>
	<?php
	printf(
		/* translators: %1$s Review, %2$s Translations, both linked to their respective page on WordPress.org */
		esc_html__( 'If you would like to contribute and share with the rest of the WordPress community, please consider writing a quick %1$s or help out with %2$s!', 'xml-sitemaps-manager' ),
		'<a href="https://wordpress.org/support/plugin/xml-sitemaps-manager/reviews/?filter=5#new-posts" target="_blank">' . esc_html__( 'Review', 'xml-sitemaps-manager' ) . '</a>',
		'<a href="https://translate.wordpress.org/projects/wp-plugins/xml-sitemaps-manager/" target="_blank">' . esc_html__( 'Translations' ) . '</a>'
	);
	?>
	<?php
	printf(
		/* translators: %s Github project page (linked) */
		esc_html__( 'For feature requests, reporting issues or contributing code, you can find and fork this plugin on %s.', 'xml-sitemaps-manager' ),
		'<a href="https://github.com/RavanH/xml-sitemaps-manager" target="_blank">' . esc_html__( 'Github', 'xml-sitemaps-manager' ) . '</a>'
	);
	?>
</p>
