<p>
	<?php echo esc_html( translate( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.' ) ); ?>
	<?php esc_html_e( 'XML sitemaps list the web pages of your site to tell search engines about the organization of your site content. Search engine web crawlers read this file to more intelligently crawl your site.', 'wp-sitemaps-manager' ); ?>
	<?php printf(
		'<a href="%s" target="_blank">%s</a>',
		esc_url( translate( 'https://www.sitemaps.org/' ) ),
		esc_html( translate( 'Learn more about XML sitemaps.' ) )
	); ?>
</p>
<p>
	<?php esc_html_e( 'When your site is public, all XML sitemaps are enabled by default. You can disable the main sitemap index or disable different types of sitemaps.', 'wp-sitemaps-manager' ); ?>
	<?php esc_html_e( 'You can adapt the maximum number of URLs per sitemap. Decrease it if you encounter errors, increase it if your sitemap index contains too many sitemaps.', 'wp-sitemaps-manager' ); ?>
	<?php esc_html_e( 'Enable Last Modified dates for all your sitemaps.', 'wp-sitemaps-manager' ); ?>
</p>